# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'Badi' do
  pod 'Kingfisher', '~> 5.13'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Badi

  target 'BadiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
